project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  # pdf: default

execute:
  freeze: true

title: "Final Project ESS330"
author:
  - name: "Yazeed Aljohani"
    email: "yazeed21@colostate.edu"
    corresponding: true
  - name: "Josh Puyear"
  - name: "Cade Vanek"

bibliography: references.bib
csl: apa.csl
